
const personalData = [
  {
    id: 1,
    title: "Persönliche Daten",
    name: "Mohammad mehdi Nafarzadeh",
    addressTitle: "Addressse:",
    address: "Mailänder 12, 60598 Frankfurt am Main",
    telephonTitle: "Telefon:",
    telephon: "+49 178 712 3740",
    emailTitle: "E-mail:",
    email: "Kayvannafarzadeh@yahoo.com",
    placeTitle: "Geburtsdatum / -ort:",
    place: "12.05.1982 / Isfahan,Iran",
    mariedTitle: "Familienstand:",
    maried: "verheiratet",
    hobbyTitle: "Hobbys",
    hobby: "Lesen, Reisen, Sport",
  },
  {
    id: 2,
    title: "Beruflicher Werdegang",
    dateActiveJob: "10/2022 – jetzt",
    activeJobTitle: "Web-Designer",
    activeJobCompany: "Firma: Arico-Machine",
    dateLastJob: "02/2021 – 03/2022",
    lastJobTitle: "Web-Designer",
    lastJobCompany: "Firma: Multi-Invest Co.(Frankfurt am Main)",
    lastJobTask1: "• Frontend Design (Joomla, Wordpress, HTML, CSS,JavaScript)",
    lastJobTask2: "• Backend Development (PHP)",
    lastJobTask3: "• Content Management (Texte, Bilder und Downloads)",
    lastJobTask4: "• Flyer Design",
    lastJobTask5: "• Bearbeitung und Erstellung von ausfüllbaren PDF Dateien",
    lastJobTask6: "• Überwachung der täglichen Datensicherungen",
    lastJobTask7: "• Regelmäßige Wiederherstellung aus Datensicherung",
    dateMiddleJob: "11/2016 – 05/2020",
    middleJobTitle: "Frontend-Entwickler",
    middleJobCompany: "Firma: Atiye Andishan Hezareye sevom Co.",
    middleJobTask1:
      "• Konzeption, Entwicklung und Umsetzung von Web-Anwendungen mit HTML5, CSS3 und JavaScript",
    middleJobTask2: "• Kontinuierliche Optimierung bestehender Frontends",
    middleJobTask3: "• Implementierung von User Interfaces",
    middleJobTask4:
      "• Implementierung von Mechanismen zur Verbesserung der Browserkompatibilität",
    middleJobTask5:
      "• Enge Zusammenarbeit mit Backend-Entwicklern und Webdesignern",
  },
  {
    id: 3,
    title: "Ausbildung",
    university: "Universität",
    ausbildungTitle: "Computeringenieurwesen - Software",
    ausbildungPlace: "Universität / Isfahan, Iran Abschluss: B.Sc",
    highschoolDate: "10/1998 – 09/2000",
    highschoolTitle: "Mathematik und Physik",
    highschoolPlace: "Gymnasium / Isfahan, Iran",
    highschoolCartificate: "Abschluss: Abitur",
  },
  {
    id: 4,
    title: "Kentnisse",
    knowledgeTitle: "EDV-Kenntnisse",
    knowledge4: "HTML5",
    knowledge5: "CSS3",
    knowledge3: "PHP",
    knowledge2: "JavaScript",
    knowledge1: "React Js",
    knowledge8: "Photoshop",
    knowledge9: "Microsoft Office",
    knowledge6: "Wordpress",
    knowledge7: "Joomla",
    languageTitle: "Sprachkenntnisse",
    lenguage1: "Deutsch (B1)",
    lenguage2: "Englisch (B1)",
    lenguage3: "Persisch (Muttersprache)",
  },
];
  const personalDataEnglisch = [
    {
      id: 1,
      title: "Personal data",
      name: "Mohammad mehdi Nafarzadeh",
      addressTitle: "Address:",
      address: "Mailänder 12, 60598 Frankfurt am Main",
      telephonTitle: "Phone:",
      telephon: "+49 178 712 3740",
      emailTitle: "E-mail:",
      email: "Kayvannafarzadeh@yahoo.com",
      placeTitle: "Date/Place of Birth:",
      place: "12.05.1982 / Isfahan,Iran",
      mariedTitle: "Marital status:",
      maried: "Married",
      hobbyTitle: "Hobbies",
      hobby: "Reading, travelling, sports",
    },
    {
      id: 2,
      title: "Professional background",
      dateLastJob: "02/2021 – 02/2022",
      lastJobTitle: "Web-Designer",
      lastJobCompany: "Company: Multi-Invest Co.(Frankfurt am Main)",
      lastJobTask1:
        "• Frontend Design (Joomla, Wordpress, HTML, CSS,JavaScript)",
      lastJobTask2: "• Backend Development (PHP)",
      lastJobTask3: "• Content Management (Text, Images and Downloads)",
      lastJobTask4: "• Flyer Design",
      lastJobTask5: "• Editing and creation of fillable PDF files",
      lastJobTask6: "• Monitoring of daily data backups",
      lastJobTask7: "• Regular restore from backup",
      dateMiddleJob: "11/2016 – 05/2020",
      middleJobTitle: "Frontend Developer",
      middleJobCompany: "Company: Atiye Andishan Hezareye sevom Co.",
      middleJobTask1:
        "• Conception, development and implementation of web applications with HTML5, CSS3 and JavaScript",
      middleJobTask2: "• Continuous optimization of existing frontends",
      middleJobTask3: "• Implementation of user interfaces",
      middleJobTask4:
        "• Implementation of mechanisms to improve browser compatibility",
      middleJobTask5:
        "• Close cooperation with backend developers and web designers",
    },
    {
      id: 3,
      title: "Education",
      university: "University",
      ausbildungTitle: "Computer Engineering - Software",
      ausbildungPlace: "University / Isfahan, Iran Degree: B.Sc",
      highschoolDate: "10/1998 – 09/2000",
      highschoolTitle: "Mathematics and Physics",
      highschoolPlace: "High school / Isfahan, Iran",
      highschoolCartificate: "Degree: High school",
    },
    {
      id: 4,
      title: "Knowledge",
      knowledgeTitle: "Computer skills",
      knowledge4: "HTML5",
      knowledge5: "CSS3",
      knowledge3: "PHP",
      knowledge2: "JavaScript",
      knowledge1: "React Js",
      knowledge8: "Photoshop",
      knowledge9: "Microsoft Office",
      knowledge6: "Wordpress",
      knowledge7: "Joomla",
      languageTitle: "linguistic proficiency",
      lenguage1: "German (B1)",
      lenguage2: "English (B1)",
      lenguage3: "Persian (Mother tongue)",
    },
  ];

export{ personalData, personalDataEnglisch};
